/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaentornos;

/**
 *
 * @author raul
 */
public class PanelesCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form PanelesCalculadora
     */
    public PanelesCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel1 = new javax.swing.JPanel();
        textouno = new javax.swing.JLabel();
        botonlimpiar = new javax.swing.JButton();
        cajauno = new javax.swing.JTextField();
        textodos = new javax.swing.JLabel();
        cajados = new javax.swing.JTextField();
        textotres2 = new javax.swing.JLabel();
        cajatres = new javax.swing.JTextField();
        botonrestar = new javax.swing.JButton();
        botonsumar = new javax.swing.JButton();
        botonmultiplicar = new javax.swing.JButton();
        botondividir = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonsuma = new javax.swing.JButton();
        botonresta = new javax.swing.JButton();
        botonmultiplica = new javax.swing.JButton();
        botondividi = new javax.swing.JButton();
        botonlimpia = new javax.swing.JButton();
        botoncerra = new javax.swing.JButton();
        numero2 = new javax.swing.JTextField();
        numero1 = new javax.swing.JTextField();
        txtresultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Panel_AlejandroVF = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numero1_Alejandro = new javax.swing.JTextField();
        numero2_Alejandro = new javax.swing.JTextField();
        Resultado_Alejandro = new javax.swing.JTextField();
        Sumar_Alejandro = new javax.swing.JButton();
        Restar_Alejandro = new javax.swing.JButton();
        Multiplicar_Alejandro = new javax.swing.JButton();
        Dividir_Alejandro = new javax.swing.JButton();
        Limpiar_Alejandro = new javax.swing.JButton();
        Salir_Alejandro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Panel_Sergio = new javax.swing.JPanel();
        etiquetaPrimerNumero_sergio = new javax.swing.JLabel();
        etiquetaSegundoNumero_sergio = new javax.swing.JLabel();
        etiquetaResultado_sergio = new javax.swing.JLabel();
        num1_sergio = new javax.swing.JTextField();
        num2_sergio = new javax.swing.JTextField();
        res_sergio = new javax.swing.JTextField();
        resta_sergio = new javax.swing.JButton();
        limpia_sergio = new javax.swing.JButton();
        suma_sergio = new javax.swing.JButton();
        multiplica_sergio = new javax.swing.JButton();
        dividir_sergio = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        botonlimpiar1 = new javax.swing.JButton();
        botonsalir3 = new javax.swing.JButton();
        division = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        botonrestar1 = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        texto1 = new javax.swing.JTextField();
        texto2 = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 4));

        jpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Raul"));

        textouno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textouno.setText("Primer Número:");

        botonlimpiar.setText("Limpiar");
        botonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiarActionPerformed(evt);
            }
        });

        cajauno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaunoActionPerformed(evt);
            }
        });

        textodos.setText("Segundo Número:");

        textotres2.setText("Resultado:");

        botonrestar.setText("Restar");
        botonrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestarActionPerformed(evt);
            }
        });

        botonsumar.setText("Sumar");
        botonsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumarActionPerformed(evt);
            }
        });

        botonmultiplicar.setText("Multiplicar");
        botonmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicarActionPerformed(evt);
            }
        });

        botondividir.setText("Dividir");
        botondividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondividirActionPerformed(evt);
            }
        });

        botonsalir.setText("Salir");
        botonsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonsalirMouseExited(evt);
            }
        });
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textodos)
                            .addComponent(textouno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajauno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(cajados)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(textotres2))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botonsalir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonlimpiar)
                            .addComponent(cajatres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonsumar)
                    .addComponent(botondividir)
                    .addComponent(botonrestar)
                    .addComponent(botonmultiplicar))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jpanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botondividir, botonlimpiar, botonmultiplicar, botonrestar, botonsalir, botonsumar});

        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textouno)
                    .addComponent(cajauno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonsumar))
                .addGap(13, 13, 13)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textodos)
                    .addComponent(cajados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonrestar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textotres2)
                    .addComponent(cajatres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonmultiplicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonsalir)
                    .addComponent(botonlimpiar)
                    .addComponent(botondividir))
                .addGap(0, 166, Short.MAX_VALUE))
        );

        getContentPane().add(jpanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Marta"));

        botonsuma.setText("Sumar");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed1(evt);
            }
        });

        botonresta.setText("Restar");
        botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestaActionPerformed1(evt);
            }
        });

        botonmultiplica.setText("Multiplcar");
        botonmultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicaActionPerformed1(evt);
            }
        });

        botondividi.setText("Dividir");
        botondividi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondividiActionPerformed1(evt);
            }
        });

        botonlimpia.setText("Limpiar");
        botonlimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiaActionPerformed1(evt);
            }
        });

        botoncerra.setText("Cerrar");
        botoncerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerraActionPerformed(evt);
            }
        });

        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese numero:");

        jLabel2.setText("Ingrese numero:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(24, 24, 24)
                                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonmultiplica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonlimpia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoncerra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botondividi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonmultiplica))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonresta)))
                    .addComponent(botonsuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botondividi)
                    .addComponent(botoncerra)
                    .addComponent(botonlimpia))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alex"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        Panel_AlejandroVF.setBorder(javax.swing.BorderFactory.createTitledBorder("Alejandro"));

        jLabel3.setText("Introducir número:");

        jLabel4.setText("Introducir número:");

        jLabel5.setText("Resultado:");

        Sumar_Alejandro.setText("Sumar");
        Sumar_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sumar_AlejandroActionPerformed(evt);
            }
        });

        Restar_Alejandro.setText("Restar");
        Restar_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restar_AlejandroActionPerformed(evt);
            }
        });

        Multiplicar_Alejandro.setText("Multiplicar");
        Multiplicar_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multiplicar_AlejandroActionPerformed(evt);
            }
        });

        Dividir_Alejandro.setText("Dividir");
        Dividir_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dividir_AlejandroActionPerformed(evt);
            }
        });

        Limpiar_Alejandro.setText("Limpiar");
        Limpiar_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_AlejandroActionPerformed(evt);
            }
        });

        Salir_Alejandro.setText("Salir");
        Salir_Alejandro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_AlejandroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_AlejandroVFLayout = new javax.swing.GroupLayout(Panel_AlejandroVF);
        Panel_AlejandroVF.setLayout(Panel_AlejandroVFLayout);
        Panel_AlejandroVFLayout.setHorizontalGroup(
            Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero2_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero1_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resultado_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Limpiar_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salir_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Restar_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sumar_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplicar_Alejandro)
                    .addComponent(Dividir_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        Panel_AlejandroVFLayout.setVerticalGroup(
            Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sumar_Alejandro)
                    .addComponent(numero1_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                        .addComponent(Restar_Alejandro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Multiplicar_Alejandro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dividir_Alejandro))
                    .addGroup(Panel_AlejandroVFLayout.createSequentialGroup()
                        .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero2_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resultado_Alejandro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_AlejandroVFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Limpiar_Alejandro)
                            .addComponent(Salir_Alejandro))))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_AlejandroVF);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fran"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);

        Panel_Sergio.setBorder(javax.swing.BorderFactory.createTitledBorder("Sergio"));

        etiquetaPrimerNumero_sergio.setText("OPERADOR 1:");

        etiquetaSegundoNumero_sergio.setText("OPERADOR 2: ");

        etiquetaResultado_sergio.setText("RESUALTADO: ");

        num1_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1_sergioActionPerformed(evt);
            }
        });

        num2_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2_sergioActionPerformed(evt);
            }
        });

        res_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_sergioActionPerformed(evt);
            }
        });

        resta_sergio.setText("-");
        resta_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resta_sergioActionPerformed(evt);
            }
        });

        limpia_sergio.setText("Borrar");
        limpia_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpia_sergioActionPerformed(evt);
            }
        });

        suma_sergio.setText("+");
        suma_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_sergioActionPerformed(evt);
            }
        });

        multiplica_sergio.setText("*");
        multiplica_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplica_sergioActionPerformed(evt);
            }
        });

        dividir_sergio.setText("/");
        dividir_sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividir_sergioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_SergioLayout = new javax.swing.GroupLayout(Panel_Sergio);
        Panel_Sergio.setLayout(Panel_SergioLayout);
        Panel_SergioLayout.setHorizontalGroup(
            Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SergioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaPrimerNumero_sergio)
                    .addComponent(etiquetaSegundoNumero_sergio)
                    .addComponent(etiquetaResultado_sergio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_SergioLayout.createSequentialGroup()
                        .addComponent(res_sergio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpia_sergio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_SergioLayout.createSequentialGroup()
                        .addComponent(num2_sergio)
                        .addGap(12, 12, 12)
                        .addComponent(multiplica_sergio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dividir_sergio))
                    .addGroup(Panel_SergioLayout.createSequentialGroup()
                        .addComponent(num1_sergio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suma_sergio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resta_sergio)))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        Panel_SergioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num1_sergio, num2_sergio});

        Panel_SergioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dividir_sergio, multiplica_sergio, resta_sergio, suma_sergio});

        Panel_SergioLayout.setVerticalGroup(
            Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SergioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrimerNumero_sergio)
                    .addComponent(num1_sergio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma_sergio)
                    .addComponent(resta_sergio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2_sergio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplica_sergio)
                    .addComponent(dividir_sergio)
                    .addComponent(etiquetaSegundoNumero_sergio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SergioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaResultado_sergio)
                    .addComponent(res_sergio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpia_sergio))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        Panel_SergioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dividir_sergio, multiplica_sergio, resta_sergio, suma_sergio});

        getContentPane().add(Panel_Sergio);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Raquel"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Jesus Requena"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Abdellah"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Jesus Garcia"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Carlos"));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Dulce"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedro"));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Hicham"));

        botonlimpiar1.setText("Limpiar");
        botonlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiar1ActionPerformed(evt);
            }
        });

        botonsalir3.setText("Salir");
        botonsalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalir3ActionPerformed1(evt);
            }
        });

        division.setText("Dividir");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        sumar.setText("Sumar");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        botonrestar1.setText("Restar");
        botonrestar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                botonrestar1AncestorRemoved(evt);
            }
        });
        botonrestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestar1ActionPerformed(evt);
            }
        });

        multiplicacion.setText("Multiplicar");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        texto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(multiplicacion))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(botonrestar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonlimpiar1)
                .addGap(52, 52, 52)
                .addComponent(botonsalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {resultado, texto2});

        jPanel14Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonlimpiar1, botonsalir3});

        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(multiplicacion)
                        .addGap(18, 18, 18)
                        .addComponent(division)
                        .addGap(18, 18, 18)
                        .addComponent(botonrestar1)
                        .addGap(18, 18, 18)
                        .addComponent(sumar)))
                .addGap(83, 83, 83)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonsalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonlimpiar1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {resultado, texto2});

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonlimpiar1, botonsalir3});

        getContentPane().add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Dario"));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Jorge"));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botonsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonsalirMouseExited

    private void botondividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondividirActionPerformed
       String suno=cajauno.getText();
        int uno=Integer.parseInt(suno);
        String sdos=cajados.getText();
        int dos=Integer.parseInt(sdos);
        int division=uno/dos;
        String restado=String.valueOf(division);
        cajatres.setText(restado);
    }//GEN-LAST:event_botondividirActionPerformed

    private void botonmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicarActionPerformed
        String suno=cajauno.getText();
        int uno=Integer.parseInt(suno);
        String sdos=cajados.getText();
        int dos=Integer.parseInt(sdos);
        int multiplo=uno*dos;
        String restado=String.valueOf(multiplo);
        cajatres.setText(restado);
    }//GEN-LAST:event_botonmultiplicarActionPerformed

    private void botonsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumarActionPerformed
        String suno=cajauno.getText();
        int uno=Integer.parseInt(suno);
        String sdos=cajados.getText();
        int dos=Integer.parseInt(sdos);
        int suma=uno + dos;
        String restado=String.valueOf(suma);
        cajatres.setText(restado);
    }//GEN-LAST:event_botonsumarActionPerformed

    private void botonrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestarActionPerformed
       String suno=cajauno.getText();
        int uno=Integer.parseInt(suno);
        String sdos=cajados.getText();
        int dos=Integer.parseInt(sdos);
        int resta=uno - dos;
        String restado=String.valueOf(resta);
        cajatres.setText(restado);
    }//GEN-LAST:event_botonrestarActionPerformed

    private void botonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiarActionPerformed
       cajauno.setText("");
        cajados.setText("");
        cajatres.setText("");
    }//GEN-LAST:event_botonlimpiarActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultadoActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        
    }//GEN-LAST:event_numero1ActionPerformed

    private void botonsumaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed1
       double num1 = Double.parseDouble(numero1.getText());
       double num2 = Double.parseDouble(numero2.getText());
       txtresultado.setText(String.valueOf(num1+num2));
    }//GEN-LAST:event_botonsumaActionPerformed1

    private void botoncerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerraActionPerformed
         System.exit(0);
    }//GEN-LAST:event_botoncerraActionPerformed

    private void botonlimpiaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiaActionPerformed1
        txtresultado.setText("");
        numero1.setText("");
        numero2.setText("");
    }//GEN-LAST:event_botonlimpiaActionPerformed1

    private void botonmultiplicaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicaActionPerformed1
        double num1 = Double.parseDouble(numero1.getText());
       double num2 = Double.parseDouble(numero2.getText());
       txtresultado.setText(String.valueOf(num1*num2));
    }//GEN-LAST:event_botonmultiplicaActionPerformed1

    private void botonrestaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestaActionPerformed1
        double num1 = Double.parseDouble(numero1.getText());
       double num2 = Double.parseDouble(numero2.getText());
       txtresultado.setText(String.valueOf(num1-num2));
    }//GEN-LAST:event_botonrestaActionPerformed1

    private void botondividiActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondividiActionPerformed1
       double num1 = Double.parseDouble(numero1.getText());
       double num2 = Double.parseDouble(numero2.getText());
       txtresultado.setText(String.valueOf(num1/num2));
    }//GEN-LAST:event_botondividiActionPerformed1

    private void cajaunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaunoActionPerformed

    private void botonlimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiar1ActionPerformed
        texto1.setText("");
        texto2.setText("");
        resultado.setText("");
    }//GEN-LAST:event_botonlimpiar1ActionPerformed

    private void botonsalir3ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalir3ActionPerformed1
        System.exit(0);
    }//GEN-LAST:event_botonsalir3ActionPerformed1

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        int a= Integer.parseInt(texto1.getText());
        int b= Integer.parseInt(texto2.getText());
        int division1= a/b;
        String cadenaDivision= String.valueOf(division1);
        resultado.setText(cadenaDivision);
    }//GEN-LAST:event_divisionActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        int a= Integer.parseInt(texto1.getText());
        int b= Integer.parseInt(texto2.getText());
        int suma= a+b;
        String cadenaSuma= String.valueOf(suma);
        resultado.setText(cadenaSuma);
    }//GEN-LAST:event_sumarActionPerformed

    private void botonrestar1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botonrestar1AncestorRemoved

    }//GEN-LAST:event_botonrestar1AncestorRemoved

    private void botonrestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestar1ActionPerformed
        int a= Integer.parseInt(texto1.getText());
        int b= Integer.parseInt(texto2.getText());
        int resta= a-b;
        String cadenaResta= String.valueOf(resta);
        resultado.setText(cadenaResta);

    }//GEN-LAST:event_botonrestar1ActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        int a= Integer.parseInt(texto1.getText());
        int b= Integer.parseInt(texto2.getText());
        int multiplicacion1= a*b;
        String cadenaMultiplicacion= String.valueOf(multiplicacion1);
        resultado.setText(cadenaMultiplicacion);
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed

    }//GEN-LAST:event_texto1ActionPerformed

    private void texto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto2ActionPerformed

    }//GEN-LAST:event_texto2ActionPerformed

    private void dividir_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividir_sergioActionPerformed
        try{
            double num1 = Double.parseDouble(num1_sergio.getText());
            double num2 = Double.parseDouble(num2_sergio.getText());
            if(num2!=0){
                double res = num1 / num2;
                String valor = String.valueOf(res);
                res_sergio.setText(valor);
            }else{
                res_sergio.setText("No dividir 0");
            }
        }catch(Exception e){
            res_sergio.setText("Error");
        }
    }//GEN-LAST:event_dividir_sergioActionPerformed

    private void multiplica_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplica_sergioActionPerformed
        try{
            double num1 = Double.parseDouble(num1_sergio.getText());
            double num2 = Double.parseDouble(num2_sergio.getText());
            double res = num1 * num2;
            String valor = String.valueOf(res);
            res_sergio.setText(valor);
        }catch(Exception e){
            res_sergio.setText("Error");
        }
    }//GEN-LAST:event_multiplica_sergioActionPerformed

    private void suma_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_sergioActionPerformed
        try{
            double num1 = Double.parseDouble(num1_sergio.getText());
            double num2 = Double.parseDouble(num2_sergio.getText());
            double res = num1 + num2;
            String valor = String.valueOf(res);
            res_sergio.setText(valor);
        }catch(Exception e){
            res_sergio.setText("Error");
        }
    }//GEN-LAST:event_suma_sergioActionPerformed

    private void limpia_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpia_sergioActionPerformed
        num1_sergio.setText("");
        num2_sergio.setText("");
        res_sergio.setText("");
    }//GEN-LAST:event_limpia_sergioActionPerformed

    private void resta_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resta_sergioActionPerformed
        try{
            double num1 = Double.parseDouble(num1_sergio.getText());
            double num2 = Double.parseDouble(num2_sergio.getText());
            double res = num1 - num2;
            String valor = String.valueOf(res);
            res_sergio.setText(valor);
        }catch(Exception e){
            res_sergio.setText("Error");
        }
    }//GEN-LAST:event_resta_sergioActionPerformed

    private void res_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_sergioActionPerformed

    }//GEN-LAST:event_res_sergioActionPerformed

    private void num2_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2_sergioActionPerformed
        num2_sergio.setText(num2_sergio.getText());
    }//GEN-LAST:event_num2_sergioActionPerformed

    private void num1_sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1_sergioActionPerformed
        num1_sergio.setText(num1_sergio.getText());
    }//GEN-LAST:event_num1_sergioActionPerformed

    private void Sumar_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sumar_AlejandroActionPerformed
       double num1 = Double.parseDouble(numero1_Alejandro.getText());
       double num2 = Double.parseDouble(numero2_Alejandro.getText());
       Resultado_Alejandro.setText(String.valueOf(num1+num2));
    }//GEN-LAST:event_Sumar_AlejandroActionPerformed

    private void Restar_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restar_AlejandroActionPerformed
       double num1 = Double.parseDouble(numero1_Alejandro.getText());
       double num2 = Double.parseDouble(numero2_Alejandro.getText());
       Resultado_Alejandro.setText(String.valueOf(num1-num2));
    }//GEN-LAST:event_Restar_AlejandroActionPerformed

    private void Multiplicar_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multiplicar_AlejandroActionPerformed
       double num1 = Double.parseDouble(numero1_Alejandro.getText());
       double num2 = Double.parseDouble(numero2_Alejandro.getText());
       Resultado_Alejandro.setText(String.valueOf(num1*num2));
    }//GEN-LAST:event_Multiplicar_AlejandroActionPerformed

    private void Dividir_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dividir_AlejandroActionPerformed
       double num1 = Double.parseDouble(numero1_Alejandro.getText());
       double num2 = Double.parseDouble(numero2_Alejandro.getText());
       Resultado_Alejandro.setText(String.valueOf(num1/num2));
    }//GEN-LAST:event_Dividir_AlejandroActionPerformed

    private void Limpiar_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_AlejandroActionPerformed
        numero1_Alejandro.setText("");
        numero2_Alejandro.setText("");
        Resultado_Alejandro.setText("");
    }//GEN-LAST:event_Limpiar_AlejandroActionPerformed

    private void Salir_AlejandroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_AlejandroActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Salir_AlejandroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelesCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelesCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelesCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelesCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelesCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dividir_Alejandro;
    private javax.swing.JButton Limpiar_Alejandro;
    private javax.swing.JButton Multiplicar_Alejandro;
    private javax.swing.JPanel Panel_AlejandroVF;
    private javax.swing.JPanel Panel_Sergio;
    private javax.swing.JButton Restar_Alejandro;
    private javax.swing.JTextField Resultado_Alejandro;
    private javax.swing.JButton Salir_Alejandro;
    private javax.swing.JButton Sumar_Alejandro;
    private javax.swing.JButton botoncerra;
    private javax.swing.JButton botondividi;
    private javax.swing.JButton botondividir;
    private javax.swing.JButton botonlimpia;
    private javax.swing.JButton botonlimpiar;
    private javax.swing.JButton botonlimpiar1;
    private javax.swing.JButton botonmultiplica;
    private javax.swing.JButton botonmultiplicar;
    private javax.swing.JButton botonresta;
    private javax.swing.JButton botonrestar;
    private javax.swing.JButton botonrestar1;
    private javax.swing.JButton botonsalir;
    private javax.swing.JButton botonsalir3;
    private javax.swing.JButton botonsuma;
    private javax.swing.JButton botonsumar;
    private javax.swing.JTextField cajados;
    private javax.swing.JTextField cajatres;
    private javax.swing.JTextField cajauno;
    private javax.swing.JButton dividir_sergio;
    private javax.swing.JButton division;
    private javax.swing.JLabel etiquetaPrimerNumero_sergio;
    private javax.swing.JLabel etiquetaResultado_sergio;
    private javax.swing.JLabel etiquetaSegundoNumero_sergio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JButton limpia_sergio;
    private javax.swing.JButton multiplica_sergio;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JTextField num1_sergio;
    private javax.swing.JTextField num2_sergio;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero1_Alejandro;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField numero2_Alejandro;
    private javax.swing.JTextField res_sergio;
    private javax.swing.JButton resta_sergio;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton suma_sergio;
    private javax.swing.JButton sumar;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    private javax.swing.JLabel textodos;
    private javax.swing.JLabel textotres2;
    private javax.swing.JLabel textouno;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
